spring.application.name=entrenador
server.port=8083

spring.datasource.url=jdbc:postgresql://ep-lively-wave-a5970vxy-pooler.us-east-2.aws.neon.tech/entrenador_bd?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RTXBxyq7vQ8H

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect